import {AllClient, ClientAddressBook} from "@/type/client/client";

export type RootStackParamList = {
  'index': undefined;
  'settings': undefined;
  'settings-locations-main': undefined;
  'settings-gallery-main': undefined;
  'settings-gallery': undefined;
  'settings-locations': undefined;
  '(auth)/auth': undefined;
  '(settings)/(settings-location)/settings-locations-main': undefined;
  '(settings)/(settings-location)/settings-locations': undefined;
  '(standart)/client/standard-main': undefined;
  '(settings)/(settings-gallery)/settings-gallery': undefined;
  '(standart)/client/stopped-visiting': undefined;
  '(standart)/client/not-visiting': undefined;
  '(chat)/(communicatie)/chatDetails': any;
  '(free)/(client)/main': undefined | string;
  '(free)/(client)/all-client': undefined | string;
  '(free)/(client)/client-list': undefined | string;
  '(free)/(client)/address-book': undefined | string;
  '(free)/(client)/creating-client': undefined | string;
  '(free)/(client)/updating-address-book': { client: ClientAddressBook };
  '(tabs)': undefined | string;
  '(free)/(client)/details/detail-main': { infoClient: AllClient };
  '(free)/(client)/details/records': { record: AllClient };
  '(free)/(client)/details/records-information': {orderID: string};
  '(free)/(client)/details/history/upcoming-history': undefined | string;
  '(free)/(client)/details/history/past-history': undefined | string;
  '(free)/(client)/details/history/canceled-history': undefined | string;
  '(welcome)/Welcome': undefined | string;
  '(profile)/(tariff)/tariff': undefined;
  'category': any;
  '(standart)/(services)/(expertise)/expertise': any;
  '(profile)/(client)/components/AllClients': undefined;
  '(settings)/(settings-gallery)/gallery-details': any;
  '(standart)/(client)/standard-main': undefined | string;
  '(Schedule)/Schedule': string | undefined;
};
